Repository noko1024/e-auto, pull requests merged in 2020-12, with the labels that each got.

#2 ログイン機能の追加
  e-auto.py
Labels: PleaseCheck

#13 コメントアウトの追加
  e-auto.py
Labels: PleaseCheck

#16 ログインシステムの修正
  e-auto.py
Labels: bug

#18 add PushButton system
  e-auto.py
Labels: PleaseCheck

#23 setup.py update
  setup.py
Labels: PleaseCheck

#21 comment out update
  e-auto.py
Labels: PleaseCheck

#24 未対応バージョンの対応の修正
  setup.py
Labels: PleaseCheck, bug

#25 ボタンクリックがうまく成功しないバグの修正
  e-auto.py
Labels: PleaseCheck, bug

#28 新しい関数の追加
  e-auto.py
Labels: PleaseCheck, bug

#29 進捗度取得の追加
  e-auto.py
Labels: PleaseCheck

#30 進捗度が100%でないlessonへの移動、終わってない問題への自動移動の追加
  e-auto.py
Labels: PleaseCheck

#32 環境自動セットアップシステムの追加
  e-auto.py
  setup.py
Labels: PleaseCheck

#34 README.mdの更新
  LICENSE.txt
  README.md
Labels: PleaseCheck

#35 セットアップシステムの更新
  setup.py
Labels: PleaseCheck
